# Generated by Django 3.2 on 2021-06-18 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfer', '0006_comment'),
        ('reservations', '0003_alter_reservation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfer.transfer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
