# Generated by Django 3.2 on 2021-06-19 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transfer', '0006_comment'),
        ('reservations', '0004_reservcart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='title',
        ),
        migrations.RemoveField(
            model_name='reservtransfer',
            name='title',
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservtransfer',
            name='transfer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transfer.transfer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservtransfer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
