# Generated by Django 3.2 on 2021-06-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_reservtransfer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='image',
        ),
        migrations.AddField(
            model_name='reservation',
            name='adminnote',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='reservation',
            name='ip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='address',
            field=models.CharField(blank=True, max_length=155),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pickup',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
